var grammarvoiceloop = {
	numStates: 21,
	start: 0, end: 20,
	transitions: [
		{from: 0, to: 2, word: "SOE" },
		{from: 0, to: 1, word: "SOM" },
		{from: 0, to: 2, word: "SPACON" },
		{from: 1, to: 4, word: "ON" },
		{from: 2, to: 3, word: "SOM" },
		{from: 3, to: 14, word: "CHANGE" },
		{from: 3, to: 13, word: "INVESTIGATE" },
		{from: 3, to: 20, word: "HI" },
		{from: 3, to: 20, word: "HELLO" },
		{from: 3, to: 12, word: "GOOD" },
		{from: 3, to: 11, word: "REPEAT" },
		{from: 4, to: 5, word: "LOOP" },
		{from: 5, to: 6, word: "ONE" },
		{from: 6, to: 10, word: "CHANGE" },
		{from: 6, to: 9, word: "INVESTIGATE" },
		{from: 6, to: 19, word: "HI" },
		{from: 6, to: 19, word: "HELLO" },
		{from: 6, to: 8, word: "GOOD" },
		{from: 6, to: 7, word: "REPEAT" },
		{from: 7, to: 17, word: "THAT" },
		{from: 7, to: 20, logp: 0},
		{from: 8, to: 19, word: "MORNING" },
		{from: 9, to: 15, word: "PARAMETER" },
		{from: 10, to: 19, word: "LIMITS" },
		{from: 11, to: 18, word: "THAT" },
		{from: 11, to: 20, logp: 0},
		{from: 12, to: 20, word: "MORNING" },
		{from: 13, to: 16, word: "PARAMETER" },
		{from: 14, to: 20, word: "LIMITS" },
		{from: 15, to: 17, word: "SPELLING" },
		{from: 16, to: 18, word: "SPELLING" },
		{from: 17, to: 20, logp: 0},
		{from: 18, to: 20, logp: 0},
		{from: 19, to: 20, logp: 0}
	]
};
