var grammarvoiceloop = {
	numStates: 34,
	start: 0, end: 33,
	transitions: [
		{from: 0, to: 14, word: "ROLL" },
		{from: 0, to: 15, word: "REPEAT" },
		{from: 0, to: 16, word: "PROCEED" },
		{from: 0, to: 16, word: "WILCO" },
		{from: 0, to: 17, word: "INVESTIGATE" },
		{from: 0, to: 18, word: "CHANGE" },
		{from: 0, to: 9, word: "SOE" },
		{from: 0, to: 9, word: "SPACON" },
		{from: 0, to: 7, word: "PLEASE" },
		{from: 0, to: 7, word: "KINDLY" },
		{from: 0, to: 8, word: "COULD" },
		{from: 0, to: 5, word: "SOM" },
		{from: 0, to: 4, word: "THIS" },
		{from: 0, to: 4, word: "HERE" },
		{from: 0, to: 3, word: "TO" },
		{from: 0, to: 3, word: "FOR" },
		{from: 0, to: 1, word: "ALL" },
		{from: 1, to: 2, word: "STATIONS" },
		{from: 2, to: 19, word: "ROLL" },
		{from: 2, to: 27, word: "REPEAT" },
		{from: 2, to: 29, word: "PROCEED" },
		{from: 2, to: 29, word: "WILCO" },
		{from: 2, to: 20, word: "INVESTIGATE" },
		{from: 2, to: 21, word: "CHANGE" },
		{from: 2, to: 10, word: "PLEASE" },
		{from: 2, to: 10, word: "KINDLY" },
		{from: 2, to: 11, word: "COULD" },
		{from: 3, to: 9, word: "SOE" },
		{from: 3, to: 9, word: "SPACON" },
		{from: 4, to: 5, word: "SOM" },
		{from: 4, to: 6, word: "IS" },
		{from: 5, to: 12, word: "ON" },
		{from: 6, to: 5, word: "SOM" },
		{from: 7, to: 18, word: "CHANGE" },
		{from: 7, to: 17, word: "INVESTIGATE" },
		{from: 7, to: 16, word: "WILCO" },
		{from: 7, to: 16, word: "PROCEED" },
		{from: 7, to: 15, word: "REPEAT" },
		{from: 7, to: 14, word: "ROLL" },
		{from: 8, to: 7, word: "YOU" },
		{from: 9, to: 24, word: "SOM" },
		{from: 9, to: 22, word: "THIS" },
		{from: 9, to: 22, word: "HERE" },
		{from: 10, to: 21, word: "CHANGE" },
		{from: 10, to: 20, word: "INVESTIGATE" },
		{from: 10, to: 29, word: "WILCO" },
		{from: 10, to: 29, word: "PROCEED" },
		{from: 10, to: 27, word: "REPEAT" },
		{from: 10, to: 19, word: "ROLL" },
		{from: 11, to: 10, word: "YOU" },
		{from: 12, to: 13, word: "LOOP" },
		{from: 13, to: 2, word: "ONE" },
		{from: 14, to: 16, word: "CALL" },
		{from: 15, to: 32, word: "THANKS" },
		{from: 15, to: 26, word: "THANK" },
		{from: 15, to: 32, word: "PLEASE" },
		{from: 15, to: 23, word: "THAT" },
		{from: 15, to: 33, logp: 0},
		{from: 16, to: 32, word: "THANKS" },
		{from: 16, to: 26, word: "THANK" },
		{from: 16, to: 32, word: "PLEASE" },
		{from: 16, to: 33, logp: 0},
		{from: 17, to: 16, word: "PARAMETER" },
		{from: 18, to: 16, word: "LIMITS" },
		{from: 19, to: 29, word: "CALL" },
		{from: 20, to: 29, word: "PARAMETER" },
		{from: 21, to: 29, word: "LIMITS" },
		{from: 22, to: 24, word: "SOM" },
		{from: 22, to: 25, word: "IS" },
		{from: 23, to: 32, word: "PLEASE" },
		{from: 23, to: 26, word: "THANK" },
		{from: 23, to: 32, word: "THANKS" },
		{from: 23, to: 33, logp: 0},
		{from: 24, to: 14, word: "ROLL" },
		{from: 24, to: 15, word: "REPEAT" },
		{from: 24, to: 16, word: "PROCEED" },
		{from: 24, to: 16, word: "WILCO" },
		{from: 24, to: 17, word: "INVESTIGATE" },
		{from: 24, to: 18, word: "CHANGE" },
		{from: 24, to: 7, word: "PLEASE" },
		{from: 24, to: 7, word: "KINDLY" },
		{from: 24, to: 8, word: "COULD" },
		{from: 25, to: 24, word: "SOM" },
		{from: 26, to: 32, word: "YOU" },
		{from: 27, to: 31, word: "THANKS" },
		{from: 27, to: 30, word: "THANK" },
		{from: 27, to: 31, word: "PLEASE" },
		{from: 27, to: 28, word: "THAT" },
		{from: 27, to: 33, logp: 0},
		{from: 28, to: 31, word: "PLEASE" },
		{from: 28, to: 30, word: "THANK" },
		{from: 28, to: 31, word: "THANKS" },
		{from: 28, to: 33, logp: 0},
		{from: 29, to: 31, word: "THANKS" },
		{from: 29, to: 30, word: "THANK" },
		{from: 29, to: 31, word: "PLEASE" },
		{from: 29, to: 33, logp: 0},
		{from: 30, to: 31, word: "YOU" },
		{from: 31, to: 33, logp: 0},
		{from: 32, to: 33, logp: 0}
	]
};
