var wordList = [
	["ALL", "AO L"], 
	["STATIONS", "S T EY SH AH N Z"], 
	["NEVER", "N EH V ER"], 
	["THE", "DH AH"], ["THE(1)", "DH AH"], ["THE(2)", "DH IY"], 
	["LESS", "L EH S"], 
	["STILL", "S T IH L"], 
	["ANYWAY", "EH N IY W EY"], 
	["HOWEVER", "HH AW EH V ER"], 
	["ANYHOW", "EH N IY HH AW"], 
	["BY", "B AY"], 
	["WAY", "W EY"], 
	["COULD", "K UH D"], 
	["YOU", "Y UW"], 
	["SO", "S OW"], 
	["WELL", "W EH L"], 
	["KINDLY", "K AY N D L IY"], 
	["PLEASE", "P L IY Z"], 
	["ROLL", "R OW L"], 
	["CALL", "K AO L"], 
	["REPEAT", "R IH P IY T"], ["REPEAT(1)", "R IY P IY T"], 
	["THAT", "DH AE T"], ["THAT(1)", "DH AH T"], 
	["PROCEED", "P R AH S IY D"], ["PROCEED(1)", "P R OW S IY D"], ["PROCEED(2)", "P ER S IY D"], 
	["WILCO", "W IH L K AA"], 
	["INVESTIGATE", "IH N V EH S T AH G EY T"], 
	["PARAMETER", "P ER AE M AH T ER"], 
	["THOUSAND", "TH AW Z AH N D"], ["THOUSAND(1)", "TH AW Z AH N"], 
	["ATE", "EY T"], 
	["FOUR", "F AO R"], 
	["DECIMAL", "D EH S AH M AH L"], 
	["SEVEN", "S EH V AH N"], 
	["THREE", "TH R IY"], 
	["ZERO", "Z IH R OW"], ["ZERO(1)", "Z IY R OW"], 
	["SIX", "S IH K S"], 
	["TWO", "T UW"], 
	["NINE", "N AY N"], 
	["FIVE", "F AY V"], 
	["ONE", "W AH N"], ["ONE(1)", "HH W AH N"], 
	["ROMEO", "R OW M IY OW"], 
	["INDIA", "IH N D IY AH"], 
	["ZULU", "Z UW L UW"], 
	["QUEBEC", "K W AH B EH K"], 
	["HOTEL", "HH OW T EH L"], 
	["YANKEE", "Y AE NG K IY"], 
	["PAPA", "P AA P AH"], 
	["GOLF", "G AA L F"], ["GOLF(1)", "G AO L F"], 
	["X", "EH K S"], 
	["RAY", "R EY"], 
	["OSCAR", "AO S K ER"], 
	["FOXTROT", "F AA K S T R AA T"], 
	["WHISKEY", "W IH S K IY"], ["WHISKEY(1)", "HH W IH S K IY"], 
	["NOVEMBER", "N OW V EH M B ER"], 
	["ECHO", "EH K OW"], 
	["VICTOR", "V IH K T ER"], 
	["MIKE", "M AY K"], 
	["DELTA", "D EH L T AH"], 
	["UNIFORM", "Y UW N AH F AO R M"], 
	["LIMA", "L AY M AH"], ["LIMA(1)", "L IY M AH"], 
	["CHARLIE", "CH AA R L IY"], 
	["TANGO", "T AE NG G OW"], 
	["KILO", "K IH L OW"], 
	["BRAVO", "B R AA V OW"], 
	["SIERRA", "S IY EH R AH"], 
	["JULIET", "JH UW L IY EH T"], 
	["ALPHA", "AE L F AH"], 
	["CHANGE", "CH EY N JH"], 
	["LIMITS", "L IH M AH T S"], ["LIMITS(1)", "L IH M IH T S"], 
	["I", "AY"], 
	["HOPE", "HH OW P"], 
	["THINK", "TH IH NG K"], 
	["THANK", "TH AE NG K"], 
	["THANKS", "TH AE NG K S"], 
	["HERE", "HH IY R"], 
	["SPEAKS", "S P IY K S"], 
	["IS", "IH Z"], ["IS(1)", "IH Z"], 
	["THIS", "DH IH S"], ["THIS(1)", "DH IH S"], 
	["SOM", "S AA M"], 
	["CALLING", "K AO L IH NG"], 
	["SPEAKING", "S P IY K IH NG"], 
	["ON", "AA N"], ["ON(1)", "AO N"], 
	["LOOP", "L UW P"], 
	["EVERYBODY", "EH V R IY B AA D IY"], 
	["EVERYONE", "EH V R IY W AH N"], 
	["FOR", "F AO R"], ["FOR(1)", "F ER"], ["FOR(2)", "F R ER"], 
	["REACHING", "R IY CH IH NG"], 
	["ADDRESSING", "AH D R EH S IH NG"], 
	["TO", "T UW"], ["TO(1)", "T IH"], ["TO(2)", "T AH"], 
	["MY", "M AY"], 
	["VERY", "V EH R IY"], 
	["DEAREST", "D IH R AH S T"], 
	["DEAR", "D IH R"], 
	["SPACON", "S P EY K AA N"], 
	["SOE", "S AW IY"] 
];
