var wordList = [
	["ALL", "AO L"], 
	["STATIONS", "S T EY SH AH N Z"], 
	["COULD", "K UH D"], 
	["YOU", "Y UW"], 
	["KINDLY", "K AY N D L IY"], 
	["PLEASE", "P L IY Z"], 
	["ROLL", "R OW L"], 
	["CALL", "K AO L"], 
	["REPEAT", "R IH P IY T"], ["REPEAT(1)", "R IY P IY T"], 
	["THAT", "DH AE T"], ["THAT(1)", "DH AH T"], 
	["PROCEED", "P R AH S IY D"], ["PROCEED(1)", "P R OW S IY D"], ["PROCEED(2)", "P ER S IY D"], 
	["WILCO", "W IH L K AA"], 
	["INVESTIGATE", "IH N V EH S T AH G EY T"], 
	["PARAMETER", "P ER AE M AH T ER"], 
	["CHANGE", "CH EY N JH"], 
	["LIMITS", "L IH M AH T S"], ["LIMITS(1)", "L IH M IH T S"], 
	["THANK", "TH AE NG K"], 
	["THANKS", "TH AE NG K S"], 
	["HERE", "HH IY R"], 
	["THIS", "DH IH S"], ["THIS(1)", "DH IH S"], 
	["IS", "IH Z"], ["IS(1)", "IH Z"], 
	["SOM", "S AA M"], 
	["ON", "AA N"], ["ON(1)", "AO N"], 
	["LOOP", "L UW P"], 
	["ONE", "W AH N"], ["ONE(1)", "HH W AH N"], 
	["FOR", "F AO R"], ["FOR(1)", "F ER"], ["FOR(2)", "F R ER"], 
	["TO", "T UW"], ["TO(1)", "T IH"], ["TO(2)", "T AH"], 
	["SPACON", "S P EY K AA N"], 
	["SOE", "S AW IY"] 
];
