var words = [
	["AFFIRMATIVE", "AH F ER M AH T IH V"], 
	["NEGATIVE", "N EH G AH T IH V"], 
	["COPY", "K AA P IY"], 
	["STANDBY", "S T AE N D B AY"], 
	["STATION", "S T EY SH AH N"], 
	["CALLING", "K AO L IH NG"], 
	["REPEAT", "R IH P IY T"], ["REPEAT(1)", "R IY P IY T"], 
	["YOUR", "Y AO R"], ["YOUR(1)", "Y UH R"], 
	["LAST", "L AE S T"], ["LAST(1)", "L AO S T"], ["LAST(2)", "L AE S"], 
	["READ", "R EH D"], ["READ(1)", "R IY D"], 
	["BACK", "B AE K"], 
	["BREAK", "B R EY K"], 
	["OUT", "AW T"], 
	["PROCEED", "P R AH S IY D"], ["PROCEED(1)", "P R OW S IY D"], ["PROCEED(2)", "P ER S IY D"], 
	["WITH", "W IH DH"], ["WITH(1)", "W IH TH"], ["WITH(2)", "W IH TH"], ["WITH(3)", "W IH DH"], 
	["PROCEDURE", "P R AH S IY JH ER"], ["PROCEDURE(1)", "P R OW S IY JH ER"], 
	["ACCORDING", "AH K AO R D IH NG"], 
	["TO", "T UW"], ["TO(1)", "T IH"], ["TO(2)", "T AH"], 
	["THE", "DH AH"], ["THE(1)", "DH AH"], ["THE(2)", "DH IY"], 
	["TIMELINE", "T AY M L AY N"], 
	["LOAD", "L OW D"], 
	["SEQUENCE", "S IY K W AH N S"], 
	["ONTO", "AA N T UW"], ["ONTO(1)", "AO N T UW"], 
	["MANUAL", "M AE N Y UW AH L"], 
	["STACK", "S T AE K"], 
	["WORD", "W ER D"], 
	["SIERRA", "S IY EH R AH"], 
	["ECHO", "EH K OW"], 
	["QUEBEC", "K W AH B EH K"], 
	["ZERO", "Z IH R OW"], ["ZERO(1)", "Z IY R OW"], 
	["SEVEN", "S EH V AH N"], 
	["ALPHA", "AE L F AH"], 
	["BRAVO", "B R AA V OW"], 
	["DISPATCH", "D IH S P AE CH"], 
	["FIRST", "F ER S T"], 
	["COMMAND", "K AH M AE N D"], 
	["DISPATCHED", "D IH S P AE CH T"], 
	["ON", "AA N"], ["ON(1)", "AO N"], 
	["LOOP", "L UW P"], 
	["COMPLETED", "K AH M P L IY T AH D"], ["COMPLETED(1)", "K AH M P L IY T IH D"], 
	["JIM", "JH IH M"], 
	["SCOTTY", "S K AA T IY"], 
	["ONE", "W AH N"], ["ONE(1)", "HH W AH N"], 
	["TWO", "T UW"], 
	["END", "EH N D"]
];
